os: linux

language: cpp
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-7-dev
    - g++-7
    update: true

env: CC_EVAL=gcc-7 CXX_EVAL=g++-7

before_install:
- export CXX=${CXX_EVAL}
- export CC=${CC_EVAL}

script:
- chmod +x ./tools/cpplint/cpplint.py
# sanitaizer check 
- ( for file in $(find ./tests -name "*.cpp"); do ./tools/cpplint/cpplint.py $file || exit; done );
- ./tools/polly/bin/polly --reconfig --toolchain sanitize-address --config Release --fwd CMAKE_EXE_LINKER="-fuse-ld=gold"
# clang-check
- ./tools/polly/bin/polly --reconfig --config Release --fwd CMAKE_EXE_LINKER="-fuse-ld=gold" CMAKE_EXPORT_COMPILE_COMMANDS=ON
- ( for file in $(find ./tests -name "*.cpp"); do echo $file; clang-check -analyze $file -p _builds/default-Release || exit; done );
# tests
- ./tools/polly/bin/polly --reconfig --test --config Release --fwd CMAKE_EXE_LINKER="-fuse-ld=gold"

# CMAKE_EXE_LINKER: https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed

notifications:
  email: false
