os: linux

language: cpp
sudo: true

notifications:
  email: false
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-7-dev
    - g++-7
    update: true

install: 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - eval "CC=/usr/bin/gcc && CXX=/usr/bin/g++"

script:
  - chmod 777 ./cpplint.py
  - ( for file in $(find ./ -name "*.cpp"); do ./cpplint.py $file || exit; done );
  - cmake -H. -B_builds -DCMAKE_EXPORT_COMPILE_COMMANDS=YES
  - cmake --build _builds
  - ( for file in $(find ../ -name "*.cpp"); do echo $file; clang-check -analyze $file -p ./ || exit; done );
  - ./executable
